# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "chenglong/manager"
  config.vm.hostname = "manager"
  config.vm.network "forwarded_port", guest: 8888, host: 8888 # manager web interface
  config.vm.network "forwarded_port", guest: 5672, host: 5672 # rabbitmq
  config.vm.network "forwarded_port", guest: 15672, host: 15672 # webinterface rabbitmq
  config.vm.network "forwarded_port", guest: 3000, host: 3000 # grafana server
end