#!/bin/bash -ex

echo "Hello World!"
echo Bootstrap/START


# sudo apt-get update

# iptables -A INPUT -p tcp --destination-port 3306 -j ACCEPT

# sudo apt-get update --fix-missing


# todo
# check if any of the following dependent list of urls are broken

echo Bootstrap/OK
echo "End of Bootstrap Script"